needings:
  Папки:
    - Получение главной папки
    - Получение папки с содержимым ( содержимое - другие папки и конспекты )
    - Создание папки/конспекта
    - Переименование папки
    - Удаление папки
  Конспекты:
    - Получение конспекта с содержимым ( содержимое - вопросы )
    - Переименование конспекта
    - Создание вопроса к конспекту
    - Удаление конспекта
  Вопросы:
    - Редактирование содержимого вопроса
    - Удаление вопроса
  Публичные конспекты:
    - Публикация конспекта +
    - Добавление публичного конспекта в "избранное" +
    - Присвоение тэга конспекту +
    - Получение списка пубоичных конспектов по тэгу +
    - Получение публичного конспекта по id +
    - Получение публичного конспекта определенного пользователя ?
    - Удаление публичного конспекта +
  Группы:
    - Создание группы +
    - Вступление в открытую группу +
    - Получение доступа к закрытой группе +
    - Добавление конспекта в группу +
    - Присовение тега к группе
  Тэги:
    Тэги будут предоставляться нами. Пользователи не смогут создавать свои, а будут только выбирать